/* eslint-disable max-len */
import React from 'react';
import { storiesOf } from '@storybook/react';

import Meta from '.';

const data = {
  node: {
    frontmatter: { date: '2019-12-04T14:20:07+0000' }, // ISO 8601 timestamp
    html: `Felis tempus mollis malesuada vehicula laoreet consequat potenti quisque, aptent ornare auctor sollicitudin blandit nunc adipiscing sem porttitor, senectus eget ultrices vivamus class ad magnis. Porta mus blandit egestas sit leo auctor nunc habitasse lobortis est, congue scelerisque montes penatibus viverra cras nisl magnis eleifend, dis nec maecenas torquent habitant mauris inceptos vel sollicitudin. Commodo cursus eu egestas porttitor ac sapien nibh et, quis taciti parturient non penatibus justo nostra. Molestie laoreet nec duis etiam ultricies maecenas consequat blandit lorem donec, proin diam faucibus aliquam torquent justo tortor adipiscing vulputate. Adipiscing mattis dictumst est elit sed eleifend ligula nisl purus gravida laoreet, mauris lacus luctus curabitur mollis natoque conubia mi lacinia maximus, arcu habitasse parturient ut nisi congue velit et cubilia ullamcorper. Finibus sapien vulputate enim potenti, eleifend lacinia volutpat dictum efficitur, mi ipsum condimentum. Pellentesque dui mus metus maecenas rutrum tristique duis egestas curabitur, tincidunt luctus ipsum lacinia interdum fringilla sollicitudin blandit pretium, ac nostra platea natoque enim ultricies quis tempus.

Torquent ornare et dignissim vehicula felis, taciti mi tincidunt accumsan fringilla at, ac tristique penatibus curae. Ut litora ultricies fringilla tempor rutrum dictumst aenean curae dis, himenaeos iaculis viverra luctus mus hendrerit magna pulvinar, vel ullamcorper vulputate felis primis diam dolor tincidunt. Proin curabitur himenaeos nisi ex lectus vehicula magna luctus vel, ultricies pharetra egestas elementum senectus primis elit nec diam, dui ipsum morbi eros mauris nostra interdum torquent. Cras leo platea convallis dui nostra habitasse ad fames nunc, nam mus lacinia mauris venenatis magnis hendrerit etiam.

Penatibus ligula tempus class nulla mi est morbi eros consequat, nascetur himenaeos tellus litora magnis quis lacinia ultrices pellentesque, turpis aliquet orci varius venenatis pulvinar justo etiam. Sit consequat torquent natoque adipiscing viverra sem ex iaculis amet aenean volutpat, orci nibh venenatis erat convallis scelerisque magna fusce nunc mattis, gravida ultricies lacus nullam metus dolor phasellus facilisis euismod aliquam. Sapien consequat ullamcorper per himenaeos accumsan bibendum lectus ipsum facilisi, vestibulum natoque suspendisse phasellus non facilisis molestie. Finibus torquent dignissim eleifend dui nullam rutrum hac aliquet auctor, ornare pretium nam feugiat est cubilia augue dolor, mattis natoque maximus sodales ipsum arcu diam turpis. Platea leo duis sagittis fames massa pellentesque aenean placerat, fringilla class vitae dapibus pharetra augue dictumst pretium dui, arcu dignissim nostra curae aptent finibus conubia. Magnis tincidunt sapien eros netus sit ornare bibendum, suscipit tortor ultrices himenaeos diam dictumst platea, suspendisse parturient phasellus magna risus senectus.

Risus ornare maecenas donec hendrerit habitant himenaeos ante, mauris condimentum habitasse consequat pulvinar penatibus facilisis metus, class eros pellentesque est lacus suspendisse. Fusce neque ligula nec eget tempus ex nascetur nunc habitant et amet nibh, condimentum vitae sapien gravida malesuada non duis mus platea ultrices magna, facilisis maecenas torquent enim ut dapibus risus congue a per est. Aenean est quis nec accumsan consectetur eros ullamcorper neque praesent, inceptos venenatis penatibus tempus class massa turpis. Inceptos consequat mattis ridiculus conubia placerat penatibus eleifend proin felis adipiscing, velit blandit vestibulum netus in quam integer augue facilisis magnis, tristique eu vel tellus iaculis venenatis elit massa ipsum. Accumsan curabitur tellus sit morbi luctus at efficitur sagittis, praesent phasellus penatibus tristique est tempor sapien, molestie himenaeos pellentesque inceptos primis suspendisse felis. Nullam est montes ipsum pharetra velit tortor netus molestie tempus pulvinar, massa ac at sociosqu habitant fusce lacinia condimentum vulputate aenean, hac nunc rutrum efficitur in accumsan laoreet leo porta. In habitant odio ipsum nec nullam augue accumsan eget, pulvinar et arcu nascetur nibh nunc sociosqu, pharetra laoreet lectus eleifend commodo efficitur maecenas. Potenti sollicitudin scelerisque class turpis magnis praesent nunc, a habitant dapibus sit morbi.

Volutpat felis montes ante magna maecenas at per mollis sociosqu cursus dapibus, cras proin ultricies commodo elit ullamcorper dictum quam ultrices venenatis neque suspendisse, eget diam natoque et taciti bibendum donec in integer ipsum. Augue platea arcu commodo ridiculus posuere varius semper, convallis leo est dolor eleifend sem nascetur taciti, purus phasellus dignissim turpis lobortis mus. Nunc nullam scelerisque vel congue vivamus interdum a viverra, ultrices himenaeos habitant rhoncus vitae purus vulputate bibendum cras, fringilla velit sapien sem nulla ad etiam. Cubilia habitant duis nec netus eu vulputate rutrum neque consectetur taciti, nam varius mollis mattis orci sit commodo eget sodales. Imperdiet hendrerit ad dignissim nascetur donec vulputate orci sem, vehicula turpis morbi est dapibus inceptos porttitor arcu, ac conubia nisi libero at mattis eros.`,
  },
};

storiesOf('Meta', module).add('Default', () => <Meta node={data.node} />);
